<?xml version="1.0" encoding="utf-8"?><Database Name="hov_library" Class="HovLibraryDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-E12UESD;Initial Catalog=hov_library;Integrated Security=True" SettingsObjectName="HovLibrary.Properties.Settings" SettingsPropertyName="hov_libraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.book" Member="books">
    <Type Name="book">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="book_details_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="book_location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="member_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="borrow_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="return_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="book_detail_book" Member="book_detail" ThisKey="book_details_id" OtherKey="id" Type="book_detail" IsForeignKey="true" />
      <Association Name="book_location_book" Member="book_location" ThisKey="book_location_id" OtherKey="id" Type="book_location" IsForeignKey="true" />
      <Association Name="member_book" Member="member" ThisKey="member_id" OtherKey="id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.book_details" Member="book_details">
    <Type Name="book_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="isbn" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="isbn13" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="authors" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="publisher" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="publish_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="page_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ratings" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="rating_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="book_detail_book" Member="books" ThisKey="id" OtherKey="book_details_id" Type="book" />
    </Type>
  </Table>
  <Table Name="dbo.book_location" Member="book_locations">
    <Type Name="book_location">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="book_location_book" Member="books" ThisKey="id" OtherKey="book_location_id" Type="book" />
    </Type>
  </Table>
  <Table Name="dbo.employee" Member="employees">
    <Type Name="employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="members">
    <Type Name="member">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="city_of_birth" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="member_book" Member="books" ThisKey="id" OtherKey="member_id" Type="book" />
    </Type>
  </Table>
</Database>